CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INTEGER NOT NULL CHECK (age >= 0),
    email VARCHAR(320) NOT NULL UNIQUE,
    is_male BOOLEAN NOT NULL
);
